name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-adeleg:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: adeleg

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      env:
        RUSTFLAGS: -D warnings
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all --verbose
    - name: Upload resulting 'adeleg'
      uses: actions/upload-artifact@v1
      with:
        name: adeleg
        path: ./target/release/adeleg.exe
